config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  
  root 'static_pages#home'
  get 'sessions/new'
  get 'signup' => 'users#new'
  get 'userguide' => 'static_pages#user_guide'
  get 'skus' => 'static_pages#skus'

  get 'login' => 'sessions#new'        #login
  post 'login' => 'sessions#create'    
  delete 'logout' => 'sessions#destroy'   
  get 'logout' => 'sessions#destroy' 

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def user_guide
  end

  def skus
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/home.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
<div class="container">
    
<nav>
    <ul class="nav navbar-nav navbar-right">
    <li><%= link_to "User Guide", userguide_path %></li>
   
<% if logged_in?%>
<li><%= link_to "Users", users_path %></li>
    <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
Account <b class="caret"></b>
</a>

<ul class="dropdown-menu">
<li><%= link_to "Profile", current_user %></li>
<li><%= link_to "Settings", edit_user_path(current_user) %></li>
 <li><%= link_to "Skus", skus_path %></li>
<li>
<%= link_to "Log out", logout_path, method: :delete %>
</li>
</ul>
</li>
<% else %>
    <li><%= link_to "Log in", login_path %></li>
<% end %>
</ul>
</nav>
</div>
</header>


<h1>Home</h1>
<h2>Welcom to OneBeat!</h2>

app/views/static_pages/skus.html.erb
<h1>Skus</h1>

app/views/static_pages/user_guide.html.erb
<h1>User Guide</h1>
<p>
    How to set buffer penatraion?
</p>